### ISSUE TITLE
initialize i in for loop

### ISSUE THREAD

**Issue by Viewgob** [LucaScheller/VFX-UsdAssetResolver#1]
Hello!
  I think I may have found a small issue.  When I compiled the fileResolver, it wasn't looping through the extensions list.  I believe it's because i isn't initialized to 0 on this line:

https://github.com/LucaScheller/VFX-UsdAssetResolver/blob/44fb597defd3c4687a313a0b28725721ef876ac1/src/FileResolver/resolverContext.cpp#L31

Thank you for sharing!

**Comment by LucaScheller** [comment]
Hey, thanks for flagging it.

I just commited your bug fix. I don't have time to actually verify it in the next two weeks as I'm taking a small break after Siggraph. Thanks for checking out the resolvers, let me know if you find any more bugs!

Cheers,
Luca
