### ISSUE TITLE
Assetresolver freezes when calling `context.RefreshFromMappingFilePath()` (from PythonExpose.ResolverContext.Initialize)

### ISSUE THREAD

**Issue by kguyaux** [LucaScheller/VFX-UsdAssetResolver#10]
I hope this is the right place for posting this issue.
I'm using the cachedresolver(A big thanks for that btw :-)  to resolve payload-versions in our usd-projects. When I submit a renderjob from houdini to our renderfarm, I dump the current mapping/caching-pairs that are in use, into a mappingfile (following this example:  https://lucascheller.github.io/VFX-UsdAssetResolver/resolvers/CachedResolver/PythonAPI.html (generate mapping.usd)). 
On the farm, I use the PythonExpose.py file to let the CachedResolver load this file, like this:
"PythonExpose.py"
``` python
class ResolverContext:

   @staticmethod
   @log_function_args
   def Initialize(context):
       mappingfile = os.getenv("AR_CACHEDRESOLVER_MAPPINGFILE", "")
       if os.path.exists(mappingfile):
           context.SetMappingFilePath(mappingfile)
           context.RefreshFromMappingFilePath()

... 
```
.. But when `context.RefreshFromMappingFilePath` gets called, the renderprocess(husk) freezes.

I tested the other method `CacheAndResolve` to test if the rest works ok, and if I thus manually provide a resolvedpath here, then I get the result I want (A render that involves a specifically pinned payloadversion).
I tried other ways by putting the above methods for reading a mappingfile, in a husk -prerender script.. But then it resolves nothing.
Am I using the API wrong, or is this a bug?

PS: I dug a bit into the code and saw that it freezes when calling `Sdf.FindAndOpen(<mappingfile>)`, I might circumvent this by dumping&loading my mappingpairs from a jsonfile. But it feels a bit like I'm using this the wrong way.

**Comment by LucaScheller** [comment]
Hey, thanks for checking out the resolver!

Mh not sure what's going wrong, I'm guessing there is some kind of recursive refresh going on, from the code I can't see why though at a first glance..

Can you try passing the mapping file via the "husk --resolver-context <path to mapping file>" flag? 
https://www.sidefx.com/docs/houdini/ref/utils/husk.html

Cheers,
Luca

**Comment by kguyaux** [comment]
Great, that worked!!
Like you said, I added: `--resolver-context "/<path>/<to>/my_usd_mapping.usda` to husk, and everything gets resolved conform the contents of the mappingfile.
Now we have something to work with :-) (i.e. a rendering-pipeline) This also prevents the need to pass everything as an ENV and add extra code to PythonExpose.
Many thanks!

**Comment by LucaScheller** [comment]
Cool! Does it also crash in Houdini if you specify the env var there? I'm wondering why husk crashes/hangs. If you add a log/print message, is it doing something recursively that would explain it?

**Comment by kguyaux** [comment]
I can confirm that Houdini also freezes when I use that (when calling `RefreshFromMappingFilePath()` in the initialize-method). 
By adding some debugmessages I came as far as this call (line 126):
https://github.com/LucaScheller/VFX-UsdAssetResolver/blob/960075deb8e22bf68b894462162e556240a59d5c/src/CachedResolver/resolverContext.cpp#L126C28-L126C38
So apparently it goes wrong after SdfLayer::FindOrOpen(<mappingfile>).
I ran it through gdb, but could not make sense of it. I'll have to reproduce those messages.. (will post later)

**Comment by BigRoy** [comment]
> I can confirm that Houdini also freezes when I use that (when calling `RefreshFromMappingFilePath()` in the initialize-method). By adding some debugmessages I came as far as this call (line 126): https://github.com/LucaScheller/VFX-UsdAssetResolver/blob/960075deb8e22bf68b894462162e556240a59d5c/src/CachedResolver/resolverContext.cpp#L126C28-L126C38 So apparently it goes wrong after SdfLayer::FindOrOpen(). I ran it through gdb, but could not make sense of it. I'll have to reproduce those messages.. (will post later)

Wouldn't opening a layer technically mean the asset resolver would end up needing to resolve the path you passed it? And thus recurse into itself?

**Comment by LucaScheller** [comment]
Good point, thanks @BigRoy  ;) I guess the file open there causes the recursive loop into the CreateContext. I'll look into putting a recursive check in there.

**Comment by kguyaux** [comment]
Ah yes, that sounds logical, good to know that is something to be aware of. Also good to know there are other ways to load the mappingfile during initialization(the argument for husk). 
I was looking for an environmental value to pass the mappingfile-location, maybe that would be a nice feature?
Thanks for the help & support! I'll close the issue if that is ok..
