### ISSUE TITLE
Layer Muting

### ISSUE THREAD

**Issue by kreppene** [LucaScheller/VFX-UsdAssetResolver#9]
Hi, thank you so much for this great resource Luca.

We are running into a problem when with the cacheResolver when it comes to layer muting.

I tried both with AR_CACHEDRESOLVER_ENV_EXPOSE_RELATIVE_PATH_IDENTIFIERS on and off, 
it seams like all paths that goes trough the resolver is affected by this.

This shows layer muting with the asset resolver
![houdinicore_assetresolver](https://github.com/LucaScheller/VFX-UsdAssetResolver/assets/7374105/cb26ced6-d82e-4ac0-82bc-eb59be2dff2a)

this shows layer muting without the assetresolver
![houdinicore_rYMWyl9QSx](https://github.com/LucaScheller/VFX-UsdAssetResolver/assets/7374105/b199efa7-f157-4f0b-9377-5a5c624151c7)

Houdini uses the UsdStage::MuteAndUnmuteLayers API  for the configure stage for muting (got this from sideFx support),
From the USD docs it says it needs the layerIdentifier, but i am not able to mute the layer using the identifier i get from cached_resolver.GetCachedRelativePathIdentifierPairs().
Infact i tryed all sorts of combinations, but nothing seams to works,  not sure if i get the wrong identifier or if theirs something missing in the asset resolver, or the pythonExpose?

https://openusd.org/dev/api/class_usd_stage.html#a8af4162fe11cc6a5f21a39e770d397c2

Any idea?

**Comment by kreppene** [comment]
Thanks Roy, i tested both variants of the path with the configure Stage node, but nothing seems to work.
In Fact i think i test all combinations i can think off.

Is it working at your end?

Unresolved path
<img width="579" alt="image" src="https://github.com/LucaScheller/VFX-UsdAssetResolver/assets/7374105/07c04e8c-21ef-49f8-b78c-f91a871edfe5">

Resovled Path
<img width="326" alt="image" src="https://github.com/LucaScheller/VFX-UsdAssetResolver/assets/7374105/b010add6-0bee-4afd-8ca6-ad9a633107c9">

**Comment by LucaScheller** [comment]
Hey, I'll look into this over the weekend.

**Comment by LucaScheller** [comment]
Hey, it works for me with the examples .usd files in the repo.

It should be the assetPath that you get in the ResolveAndCache.

Is it possible for you to share the scene file and resolver (or a simplified version thereof)?

All the best,
Luca

**Comment by LucaScheller** [comment]
Notes from private chat: It happens on Windows only, strangely enough the Houdini Scene Graph layers panel is also affected. I'll debug this some more later this week.

**Comment by LucaScheller** [comment]
Issue is fixed in the [v0.6.2](https://github.com/LucaScheller/VFX-UsdAssetResolver/releases/tag/v0.6.2) release :) Let me know if it works, and I'll close the issue.

The problem was (the usual ;) ) Window path separator conversion. [You can also just fix this line in your PythonExpose.py file.](https://github.com/LucaScheller/VFX-UsdAssetResolver/commit/960075deb8e22bf68b894462162e556240a59d5c)

**Comment by kreppene** [comment]
This fixes the problems i have had with muting, Thanks Luca.
Please go ahead and close this issue
